import React from 'react';
import Paper from '@mui/material/Paper';
import Typography from '@mui/material/Typography';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import CloudDownloadIcon from '@mui/icons-material/CloudDownload';
import DataObjectIcon from '@mui/icons-material/DataObject';
import SideBar from '../componennts/SideBar';
import ArrowForwardIosIcon from '@mui/icons-material/ArrowForwardIos';
import LanguageIcon from '@mui/icons-material/Language';
import SearchIcon from '@mui/icons-material/Search';

import { Box, useTheme, useMediaQuery, Container } from '@mui/material';
export default function Pin(){
    const theme = useTheme();
    const isSmallScreen = useMediaQuery(theme.breakpoints.down('sm'));

    const commonPaperStyle = {

        display: 'flex',
        flexGrow:"3",
        flexDirection: 'column',
        width: isSmallScreen ? '90%' : '50%',
        padding: '20px',
        margin: '16px',
        backgroundColor: '#0D121D',
        color: 'white',
        borderRadius: '15px',
      };
    return(
        <Box>
            <SideBar/>
            <Container sx={{marginLeft: { xs: 'auto', sm: isSmallScreen ? 'auto' : 35 }}}>

                <Box sx={{display:"flex"}}>
                <Paper elevation={3} style={commonPaperStyle}>
                    <Typography variant="h6">Welcome Alex</Typography>
                    <Typography variant="body1">
                    You can download string from here.
                    </Typography>
                    <Button variant="outlined" style={{ border: '2px solid gray', marginTop: '16px', alignSelf: 'flex-end' }}>
                    <CloudDownloadIcon style={{ marginRight: '8px' }} />
                    Download
                    </Button>
                </Paper>
                </Box>
            

      <Box sx={{ display: 'flex' }}>
        <Paper elevation={3} style={commonPaperStyle}>
          <div style={{ display: 'flex', alignItems: 'center', marginBottom: '16px' }}>
            <DataObjectIcon style={{ marginRight: '8px', color: 'gray' }} />
            <Typography variant="h6">Pins Generated</Typography>
          </div>
          <Typography variant="body1">
            Number of pins generated by you
          </Typography>
        </Paper>

        <Paper elevation={3} style={commonPaperStyle}>
          <div style={{ display: 'flex', alignItems: 'center', marginBottom: '16px' }}>
            <DataObjectIcon style={{ marginRight: '8px', color: 'gray' }} />
            <Typography variant="h6">Used Pins</Typography>
          </div>
          <Typography variant="body1">
            Number of pins you have used
          </Typography>
        </Paper>

        <Paper elevation={3} style={commonPaperStyle}>
          <div style={{ display: 'flex', alignItems: 'center', marginBottom: '16px' }}>
            <DataObjectIcon style={{ marginRight: '8px', color: 'gray' }} />
            <Typography variant="h6">Total Pins Used</Typography>
          </div>
          <Typography variant="body1">
            Total number of pins used
          </Typography>
        </Paper>
      </Box>

      <Box sx={{ display: 'flex' }}>
        <Paper elevation={3} style={commonPaperStyle}>
          <label htmlFor="copy-button">
            <input name="copy-button" aria-label="copy-button" placeholder="Search Pins." />
            <SearchIcon id="right-icon" />
          </label>

          {/* Add the texts in a form row with proper margin */}
          <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '16px' }}>
            <span style={{ marginRight: '20px' }}>ID</span>
            <span style={{ marginRight: '20px' }}>PIN</span>
            <span style={{ marginRight: '20px' }}>USED</span>
            <span style={{ marginRight: '20px' }}>RESULT</span>
            <span style={{ marginRight: '20px' }}>LINK</span>
            <span style={{ marginRight: '20px' }}>TYPE</span>
            <span>PRIVATE</span>
          </div>
        </Paper>
      </Box>

            </Container>
        </Box>
    )
}